apiVersion: v1
kind: Secret
metadata:
  name: gitlab-gitlab-gitlab-runner-secret
  namespace: gitlab
  annotations:
    checkov.io/skip1: CKV_K8S_21=False positive. Namespace is defined but Checkov fails to parse SOPS file.
type: Opaque
stringData:
  runner-token: ENC[AES256_GCM,data:2ci95U2Z/QVoCXPqzKzcF6UdbZdW+5zyaMK2A/G5tDxHpvgSKynTYmRFYu0Tx5Yl/3CZ7/69ERc=,iv:VSprYb/NSUGFStwHbveHTAPoAILB2yUrTf2OnlZ0i+8=,tag:cNF8TIDw33wMCx0q0I/+Wg==,type:str]
sops:
  age:
    - recipient: age1f70m834v0d5scfgvur7kakl06dvgdctafh64xc2p3xssu2msr9tq3pyfe7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSStKRmtsNExDemFHTFlk
        OWJ3dkRQKzFBaUhpRFIzUWp4WnFsTnhrU3dNCmNGZFMxSFhPN3huNnh5RHhzb0tm
        RkNIUC9oNFZtZXY5b2dDSzRISU9HL2cKLS0tIFZsQ3JIU0dMd2VzU1ZGbEpoMkxv
        blVjYm56bjNxaFpiS0hqQlRNcjVYS3cKnLvZX7Ghr6IPQ2p8CilCyTXQ9n8Y3fjw
        M2FaPiHD5C31lV7qXDAHG+5kBcqsBvyIjPq6BBZCtfpUVWo9JiNKKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-14T20:24:16Z"
  mac: ENC[AES256_GCM,data:e1/WBk54kOcHHD3TixCY0sP/gngDGS2r3N3q604RciNVnRmrOM4ru+niuuQcFDbuTv5ckswWOGvaf4bS1+4fI6PzV2j6ThHFAu0XzP2ggcadPAItIdtV8JXm8xgahOVR2FhsZctxO75rNrzvjtJbtb+/lA8VJkDQRfNpxM/ie1w=,iv:oG3jSRxwnd0RDgCwjc9WQ8SKHpWXLvRZ5UmO/Aini7w=,tag:qvJltN7V3kVSDHOEzgmXGA==,type:str]
  encrypted_regex: ^(data|stringData|spec)$
  version: 3.11.0
