apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-certs
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system

  path: ./gitops/flux/infrastructure/certs
  prune: true
  wait: true

  decryption:
    provider: sops
    secretRef:
      name: sops-age

  dependsOn:
    - name: infrastructure
