kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: iscsi-test
  namespace: default
spec:
  storageClassName: freenas-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
