apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: prod-pool
  namespace: kube-system
  annotations:
    checkov.io/skip1: CKV_K8S_21=False positive. Namespace is defined but Checkov fails to parse SOPS file.
spec:
  blocks:
    - start: ENC[AES256_GCM,data:YzPjOO5Cq0VbDWk=,iv:Vvw8ILmDMtUyrdGrsZaLh9CBYZ4tjOo0RRuVRjfnSFg=,tag:Scw9fgpMZjqtVD/+rTXCtQ==,type:str]
      stop: ENC[AES256_GCM,data:56bieY+u/7oSuv8=,iv:ErnRg6y0cDHL1Dh4u8BRvzlpeMpz9rooYMMqUM6vBXA=,tag:Q85Xy6eTol9kYsM0PQe5AA==,type:str]
sops:
  age:
    - recipient: age1f70m834v0d5scfgvur7kakl06dvgdctafh64xc2p3xssu2msr9tq3pyfe7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTVlZNFZpRzRMZHhldEFn
        Q1I4TGFRUENnUUMyVW5JWFo4eFU5anlpSWlvCmh1K3YzWTI2Q1dDTlZhMHcydTJ5
        clZZeUIwRU9aRWJjOEo0b2NBaTZWNXMKLS0tIFBkbE1tcElrUFpicG5DZkE3Qmt3
        c0ZYMi9jazhFNEpuVURRdTJhSUlBZ0EKKhEvDPT3F4oLb31s9kK9NHvkpjbB0e1o
        A5m28BwdULZOILMN1okKKYbMRhyvumVqi3ODdAoWM6rcENGQ64+wgw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T21:32:56Z"
  mac: ENC[AES256_GCM,data:aJDgmfKUn+yjNLywnQNjtDrZz5zS/E1BDm54V/IpVL/EAS9a4jnz725tN8zAB2NYRNEP6XLF/ESyuGaGlxBT48TK6thcA+8YIPLzhwiBvN6jt/iI49j9u/+8i+V2MkeMtFNA33JRTGJwCXQWyWzltGB34SSjbC7oI1u5CDgd6YA=,iv:F/Cz1LFnGmijTL+vWOx+AJMWejVhXwKIsijTsfIGSJo=,tag:e2pkeoaQEkFhu+HdXiuFNw==,type:str]
  encrypted_regex: ^(data|stringData|spec)$
  version: 3.11.0
