apiVersion: v1
kind: Secret
# checkov:skip=CKV_K8S_21:False positive. Namespace is defined but Checkov fails to parse SOPS file.
metadata:
  name: gitlab-smtp-password
  namespace: gitlab
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:IkDOkF0BSIjGTZcOZrIZ/w==,iv:gtgro/lZIsz5gxttM93Q4rKRmvyu4vFNbkkPAQuJ5L0=,tag:Wi5zMa2BuSH7SqYOdJLTwQ==,type:str]
sops:
  age:
    - recipient: age1f70m834v0d5scfgvur7kakl06dvgdctafh64xc2p3xssu2msr9tq3pyfe7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVkorenppcjhHU1E0TSth
        dmZ4SllVOHNCVnZJZStUTXBxenVoOFdBU0Y4Cm1PbWtwUVc1c0ZGczlOT1k0S295
        MC93K3VVcEZrMXhyWGgwV3ZUMHZ1UWMKLS0tIDVBSDRmVk0xQUxUMmsxcmcwTko4
        eGNnTG40b2lvZmpxYW9oQmFYM2pDaTQK7BYWZxn3YvXDYVlas8dPGOixQ5I87zsb
        xn/yQF7ynta3OKpFoJrw6wDe0klheM+8F11lsh/cRrmm4ivD83agWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T08:09:04Z"
  mac: ENC[AES256_GCM,data:LsM5LARAOjY0cYN/QSqURGlFQ8gqpKPy9hDc29+ZLQbwdpcEmjfMRj8cga6XG/Tq61LiE5YIhXgVNOt4w4LvxboNqaR+m2JMKNQGV5F0+Uye4PKvxVI/z0Z0kNgjBb/serA+dPPY2qtu/zHSnv5a97NDhUI2sEeZbBRkCE0dHKU=,iv:dLohKc7ebBaHBC9MUtXLg8CmAVbrVoUzfEsO3Db/uSc=,tag:og/cZ8fFu6d2Tl1OQvI0sA==,type:str]
  encrypted_regex: ^(data|stringData|spec)$
  version: 3.11.0
