apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: gitlab
      version: "9.6.1"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system

  targetNamespace: gitlab
  install:
    createNamespace: true
  timeout: 20m

  values:
    global:
      edition: ce
      hosts:
        domain: git.vollbro.se
        https: true

      ingress:
        configureCertmanager: true
        class: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"

      storageClass: nfs-client
    certmanager-issuer:
      email: "wollbro90@gmail.com"

    certmanager:
      enabled: false
    nginx-ingress:
      enabled: false
    prometheus:
      enabled: false
    gitlab-runner:
      install: true
    postgresql:
      install: true
      primary:
        volumePermissions:
          enabled: false

        podSecurityContext:
          fsGroup: 0
          runAsUser: 0

        containerSecurityContext:
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
          capabilities:
            add: ["CHOWN", "DAC_OVERRIDE", "FOWNER"]
    redis:
      install: true
