apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: gitlab
      version: "9.6.1"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system

  targetNamespace: gitlab
  install:
    createNamespace: true
  timeout: 20m

  values:
    global:
      edition: ce

      email:
        from: "wollbro90@gmail.com"
        display_name: "GitLab Homelab"
        reply_to: "no-reply@git.vollbro.se"

      smtp:
        enabled: true
        address: "smtp.gmail.com"
        port: 587
        user_name: "wollbro90@gmail.com"
        password:
          secret: "gitlab-smtp-password"
          key: "password"
        domain: "smtp.gmail.com"
        authentication: "login"
        starttls_auto: true
        openssl_verify_mode: "peer"

      minio:
        enabled: false

      registry:
        name: registry.vollbro.se
        storage:
          secret: gitlab-minio-connection
          key: connection
          extraConfig:
            redirect:
              disable: true

      shell:
        port: 22

      hosts:
        domain: vollbro.se
        ssh: git.vollbro.se

        gitlab:
          name: git.vollbro.se

        registry:
          name: registry.vollbro.se

        kas:
          name: kas.vollbro.se

        https: true

      appConfig:
        object_store:
          enabled: true
          proxy_download: true

          connection:
            secret: gitlab-minio-connection
            key: connection

          objects:
            artifacts:
              bucket: gitlab-artifacts
            lfs:
              bucket: gitlab-lfs
            uploads:
              bucket: gitlab-uploads
            packages:
              bucket: gitlab-packages
            dependencyProxy:
              bucket: gitlab-dependency-proxy
            terraformState:
              bucket: gitlab-terraform-state
            pages:
              bucket: gitlab-pages

        backups:
          bucket: gitlab-backups
          tmpBucket: gitlab-tmp
          keep_time: 604800

      ingress:
        configureCertmanager: false
        class: nginx
        tls:
          enabled: true
          secretName: gitlab-gitlab-wildcard-tls-v2

      storageClass: freenas-iscsi

    certmanager-issuer:
      email: "wollbro90@gmail.com"

    certmanager:
      enabled: false
    nginx-ingress:
      enabled: false
    prometheus:
      enabled: false
    gitlab-runner:
      install: true
    postgresql:
      install: true
    redis:
      install: true

    gitlab:
      toolbox:
        replicas: 1
        backups:
          objectStorage:
            config:
              secret: gitlab-backup-s3cfg
              key: config

          cron:
            enabled: true
            schedule: "0 2 * * *"
            # extraArgs: "--skip registry"
            suspend: false
            concurrencyPolicy: Forbid
            failedJobsHistoryLimit: 1
            successfulJobsHistoryLimit: 3

      webservice:
        minReplicas: 1
        maxReplicas: 1
        replicaCount: 1
        resources:
          requests:
            memory: 800Mi
            cpu: 300m
          limits:
            memory: 3Gi

      sidekiq:
        minReplicas: 1
        maxReplicas: 1
        resources:
          requests:
            memory: 500Mi
            cpu: 200m

      gitlab-shell:
        service:
          type: ClusterIP
        minReplicas: 1
        maxReplicas: 1
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
