apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: gitlab
      version: "9.6.1"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system

  targetNamespace: gitlab
  install:
    createNamespace: true
  timeout: 20m

  values:
    global:
      edition: ce
      hosts:
        domain: vollbro.se

        gitlab:
          name: git

        registry:
          name: registry

        minio:
          name: minio

        kas:
          name: kas

        https: true

      ingress:
        configureCertmanager: true
        class: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"

      storageClass: freenas-iscsi
    certmanager-issuer:
      email: "wollbro90@gmail.com"

    certmanager:
      enabled: false
    nginx-ingress:
      enabled: false
    prometheus:
      enabled: false
    gitlab-runner:
      install: true
    postgresql:
      install: true
    redis:
      install: true

    gitlab:
      webservice:
        minReplicas: 1
        maxReplicas: 1
        replicaCount: 1
        resources:
          requests:
            memory: 800Mi
            cpu: 300m
          limits:
            memory: 3Gi

      sidekiq:
        minReplicas: 1
        maxReplicas: 1
        resources:
          requests:
            memory: 500Mi
            cpu: 200m

      gitlab-shell:
        minReplicas: 1
        maxReplicas: 1
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
