apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      version: "v1.18.1"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system

  targetNamespace: cert-manager
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace

  values:
    installCRDs: true

    prometheus:
      enabled: false
    webhook:
      timeoutSeconds: 4
