apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: prod-pool
  namespace: kube-system
  annotations:
    checkov.io/skip1: CKV_K8S_21=False positive. Namespace is defined but Checkov fails to parse SOPS file.
spec:
  blocks:
    - start: ENC[AES256_GCM,data:YzPjOO5Cq0VbDWk=,iv:Vvw8ILmDMtUyrdGrsZaLh9CBYZ4tjOo0RRuVRjfnSFg=,tag:Scw9fgpMZjqtVD/+rTXCtQ==,type:str]
      stop: ENC[AES256_GCM,data:FgAUd04dprxzmEc=,iv:00L10apMGfK2O3lNbuGQHH5lwDxcEOdZywV8qmSs1VI=,tag:TjLQTRYpRUUn5xKy2E580A==,type:str]
sops:
  age:
    - recipient: age1f70m834v0d5scfgvur7kakl06dvgdctafh64xc2p3xssu2msr9tq3pyfe7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTVlZNFZpRzRMZHhldEFn
        Q1I4TGFRUENnUUMyVW5JWFo4eFU5anlpSWlvCmh1K3YzWTI2Q1dDTlZhMHcydTJ5
        clZZeUIwRU9aRWJjOEo0b2NBaTZWNXMKLS0tIFBkbE1tcElrUFpicG5DZkE3Qmt3
        c0ZYMi9jazhFNEpuVURRdTJhSUlBZ0EKKhEvDPT3F4oLb31s9kK9NHvkpjbB0e1o
        A5m28BwdULZOILMN1okKKYbMRhyvumVqi3ODdAoWM6rcENGQ64+wgw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T22:20:56Z"
  mac: ENC[AES256_GCM,data:eAPYEiII8o68RrtZ+a77JzECN/jaygiQFelORRNeWldOucbz316NprMYwLPvfrxqgdU0pGcAiYggRGAGMyQUwvyICOhEj8h2VEcPF5JTm0MvqsPf2vX4DV26u6nL/LzvfHeDE0WNURXgUY+7Sil+8lBQwouMas0l2DETpzRJmaA=,iv:BeY6BZqINWErsInOjtEuGfdtSV8WvbISz7cbCZ0Rlg0=,tag:73V+5q1mC6syt+juG2RWOQ==,type:str]
  encrypted_regex: ^(data|stringData|spec)$
  version: 3.11.0
