---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: reflector
      version: "v9.1.45"
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
  targetNamespace: kube-system
  install:
    createNamespace: true
