apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-controllers
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/flux/infrastructure/controllers/overlays/staging
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
